main:
  params: [input]
  steps:
    - parallelProcessing:
        parallel:
          branches:
            - opaPropertiesBranch:
                steps:
                  - extractOpaPropertyData:
                      call: http.post
                      args:
                        url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/extract_opa_properties'
                        auth:
                          type: OIDC
                  - prepareOpaPropertyData:
                      call: http.post
                      args:
                        url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/prepare_opa_properties'
                        auth:
                          type: OIDC
                  - loadOpaPropertyData:
                      call: http.get
                      args:
                        url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/load-opa-properties'
                        auth:
                          type: OIDC

            - opaAssessmentsBranch:
                steps:
                  - extractOpaAssessmentsData:
                      call: http.post
                      args:
                        url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/extract_opa_assessments'
                        auth:
                          type: OIDC
                  - prepareOpaAssessmentsData:
                      call: http.post
                      args:
                        url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/prepare_opa_assessments'
                        auth:
                          type: OIDC
                  - loadOpaAssessmentsData:
                      call: http.get
                      args:
                        url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/load-opa-assessments'
                        auth:
                          type: OIDC

            - pwdParcelsBranch:
                steps:
                  - extractPwdParcels:
                      call: http.post
                      args:
                        url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/extract_pwd_parcels'
                        auth:
                          type: OIDC
                  - preparePwdParcels:
                      call: http.post
                      args:
                        url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/prepare_pwd_parcels'
                        auth:
                          type: OIDC
                  - loadPwdParcels:
                      call: http.get
                      args:
                        url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/load-pwd-parcels'
                        auth:
                          type: OIDC

    - createTaxYearAssessmentTable:
        call: http.post
        args:
          url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/generate-assessment-chart-configs'
          auth:
            type: OIDC
    
    - trainModel:
        call: http.post
        args:
          url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/ml_model_train'
          auth:
            type: OIDC

    - applyModel:
        call: http.post
        args:
          url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/ml_model_apply'
          auth:
            type: OIDC

    - createCurrentAssessmentTable:
        call: http.post
        args:
          url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/generate-current-assessment-chart-configs'
          auth:
            type: OIDC

    - createHistoricalChartConfig:
        call: http.post
        args:
          url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/generate-assessment-chart-configs'
          auth:
            type: OIDC

    - createCurrentChartConfig:
        call: http.post
        args:
          url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/generate-current-assessment-chart-configs'
          auth:
            type: OIDC

    - createTableWithPredictions:
        call: http.post
        args:
          url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/create_pwd_table_with_prediccs'
          auth:
            type: OIDC

    - createGeojsonOutput:
        call: http.post
        args:
          url: 'https://us-east4-musa5090s25-team1.cloudfunctions.net/write_geojson_with_prediccs'
          auth:
            type: OIDC

    - execute_pbf_job:
        call: googleapis.run.v2.projects.locations.jobs.run
        args:
          name: "projects/musa5090s25-team1/locations/us-east4/jobs/generate-property-tiles"
          body: {}